language: ruby
rvm:
  - 2.5.5
before_script:
  - chmod +x ./script/cibuild
bundle:
  - 2.0
script: ./script/cibuild #"bundle exec jekyll build"
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of
    # html-proofer

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  local_dir: _site/
  github_token: $GITHUB_API_KEY
  on:
    branch: master
