# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Countable Smorgasbord"
description: "most things are broken most of the time"
#description: "trying to not be lost using math, while not getting lost in the math either"
baseurl: "" # the subpath of your site, e.g. "/blog"
url: "" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "images/laughing_man_inkscape_black_White.svg" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 187
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: dsweber21 # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  math_engine: mathjax
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 5
# paginate_path: /_blog/page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-katex

katex:
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: 
  picture: 
  email:
  twitter: 
  links: false

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/dsweber2
    icon: fab fa-github-square
  - title: ArXiv
    url: https://arxiv.org/search/?query=Weber%2C+David&searchtype=author&abstracts=show&order=-announced_date_first&size=50
    icon: fas fa-university
  - title: Goodreads
    url: https://www.goodreads.com/review/list/53990322
    icon: fab fa-goodreads
  - title: Twitter
    url: https://twitter.com/dsweber21
    icon: fab fa-twitter-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
